---
title: "Practical Exam-22575480"
documentclass: elsarticle
Thesis_FP: no
output:
  html_document:
    df_print: paged
  pdf_document:
    keep_tex: yes
    template: Tex/TexDefault.txt
    fig_width: 3.5
    fig_height: 3.5
Author1: null
Ref1: Some Institution, Cape Town, South Africa
Email1: nfkatzke\@gmail.com
Author2: John Smith
Ref2: Some other Institution, Cape Town, South Africa
Email2: John\@gmail.com
CommonAffiliation_12: yes
Author3: John Doe
Email3: Joe\@gmail.com
CorrespAuthor_1: yes
keywords: Multivariate GARCH \sep Kalman Filter \sep Copula
JELCodes: L250 \sep L100
BottomRFooter: \footnotesize Page \thepage
addtoprule: yes
addfootrule: yes
margin: 2.3
bottom: 2
top: 2.5
HardSet_layout: yes
linenumbers: no
bibliography: Tex/ref.bib
csl: "Tex/harvard-stellenbosch-university.csl"
RemovePreprintSubmittedTo: yes
Journal: Journal of Finance
toc: no
numbersections: yes
fontsize: 11pt
linestretch: 1.2
link-citations: yes
AddTitle: yes
---

<!-- First: Set your default preferences for chunk options: -->

<!-- If you want a chunk's code to be printed, set echo = TRUE. message = FALSE stops R printing ugly package loading details in your final paper too. I also suggest setting warning = FALSE and checking for warnings in R, else you might find ugly warnings in your paper. -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')
# Note: Include = FALSE implies the code is executed, but not printed in your pdf.
# warning and message = FALSE implies ugly messages and warnings are removed from your pdf.
# These should be picked up when you execute the command chunks (code sections below) in your rmd, not printed in your paper!

# Lets load in example data, and see how this can be stored and later called from your 'data' folder.
if(!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)
library(scales)
library(huxtable)
```


<!-- ############################## -->
<!-- # Start Writing here: -->
<!-- ############################## -->

Question 1
```{r}
#read in data 
covid_data<-read.csv("/Users/ryanyoung/Desktop/Data Science/22575480/data/data/Covid/owid-covid-data.csv")
prior_data<-read.csv("/Users/ryanyoung/Desktop/Data Science/22575480/data/data/Covid/Deaths_by_cause.csv")
combined_data<-bind_rows(covid_data,prior_data)
```

```{r}
#total deaths per million
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 1/code/total_deaths_bar.R")
chart <- create_mean_deaths_bar_chart(covid_data)
chart
```

```{r}
#covid deaths by life expectancy 
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 1/code/create_scatter_plot.R")

create_scatter_plot(covid_data)

```

```{r}
#covids deaths by percent of population over 65
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 1/code/create_scatter_plot_2.R")

create_scatter_plot_2(covid_data)
```

```{r}
#hospitals admission chart
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 1/code/patient_admissions_chart.R")
chart <- create_admissions_line_chart(covid_data)
chart
```

Question 2

```{r}
# load in data:
london_weather <- read_csv("/Users/ryanyoung/Desktop/Data Science/22575480/Question 2/data/london_weather.csv")

```

```{r}
#convert date column
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 2/code/convert_date_column.R")
london_weather <- convert_date_column(london_weather, "date")
```

```{r}
#line chart minimum temp
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 2/code/line_chart_temp.R")
plot_daily_min_temperature(london_weather)
```

```{r}
#daily mean temp
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 2/code/plot_daily_temp.R")
plot_mean_temperature(london_weather)
```

```{r}
#precipitation bar chat
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 2/code/plot_daily_precipitation.R")
b<- plot_daily_precipitation(london_weather)
b
```

Question 3

```{r}
#read in the data
coldplay <- read.csv("/Users/ryanyoung/Desktop/Data Science/22575480/Question 3/data/Coldplay_vs_Metallica/Coldplay.csv")
metallica<-read.csv("/Users/ryanyoung/Desktop/Data Science/22575480/Question 3/data/Coldplay_vs_Metallica/metallica.csv")
spotify<-read.csv("/Users/ryanyoung/Desktop/Data Science/22575480/Question 3/data/Coldplay_vs_Metallica/Broader_Spotify_Info.csv")

```

```{r}
#filter songs
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 3/code/filter_songs.R")
metallica_refined <- filter_songs(metallica)
```

```{r}
#box and whisker for tempo (live vs non live) metallica
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 3/code/box_whisker_live.R")

plot_live_vs_nonlive_tempo(metallica)
```

```{r}
#box and whisker for tempo (live vs non live) coldplay
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 3/code/box_whisker_live.R")

plot_live_vs_nonlive_tempo(coldplay)
```

```{r}
#Popularity over time metallica
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 3/code/line_plot_ popularity.R")
plot_popularity_over_time(metallica_refined)
```

```{r}
#Popularity over time coldplay
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 3/code/line_plot_ popularity.R")
plot_popularity_over_time(coldplay)
```


```{r}
#top songs by energy table
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 3/code/table_energy.R")
top_songs_table <- create_top_songs_table(spotify, 10)
print(top_songs_table)
```

Question 4

```{r}
#read in the data
netflix<-read.csv("/Users/ryanyoung/Desktop/Data Science/22575480/data/data/netflix/titles.csv")
```

```{r}
#movie release by year
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 4/code/movies_per_year.R")
plot_movies_released(netflix)
```

```{r}
#average scores after 2000
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 4/code/line_chart_score.R")
plot_average_scores(netflix)
```

```{r}
#table showing age rating 
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 4/code/movie_table_age.R")
movie_counts <- get_movie_counts_by_age(netflix)
movie_counts
```

Question 5

```{r}
#read in the data
googleplay<-read.csv("/Users/ryanyoung/Desktop/Data Science/22575480/data/data/googleplay/googleplaystore.csv")
user_reviews<-read.csv("/Users/ryanyoung/Desktop/Data Science/22575480/data/data/googleplay/googleplaystore_user_reviews.csv")
```


```{r}
#bubble chart (use bubble chart 2)
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 5/code/Bubble_chart_2.R")
chart <- create_bubble_chart(googleplay)
chart
```

```{r}
#table showing popularity by genre 
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 5/code/popularity_table.R")
result <- get_average_ratings_downloads(googleplay)
result
```

