---
title: "Helping You Write Academic Papers in R using Texevier"
documentclass: elsarticle
Thesis_FP: no
output:
  html_document:
    df_print: paged
  pdf_document:
    keep_tex: yes
    template: Tex/TexDefault.txt
    fig_width: 3.5
    fig_height: 3.5
Author1: Jane Doe^[__Contributions:__  \newline _The authors would like to thank no
  institution for money donated to this project. Thank you sincerely._]
Ref1: Some Institution, Cape Town, South Africa
Email1: nfkatzke\@gmail.com
Author2: John Smith
Ref2: Some other Institution, Cape Town, South Africa
Email2: John\@gmail.com
CommonAffiliation_12: yes
Author3: John Doe
Email3: Joe\@gmail.com
CorrespAuthor_1: yes
keywords: Multivariate GARCH \sep Kalman Filter \sep Copula
JELCodes: L250 \sep L100
BottomRFooter: \footnotesize Page \thepage
addtoprule: yes
addfootrule: yes
margin: 2.3
bottom: 2
top: 2.5
HardSet_layout: yes
linenumbers: no
bibliography: Tex/ref.bib
csl: "Tex/harvard-stellenbosch-university.csl"
RemovePreprintSubmittedTo: yes
Journal: Journal of Finance
toc: no
numbersections: yes
fontsize: 11pt
linestretch: 1.2
link-citations: yes
AddTitle: yes
abstract: |
  Abstract to be written here. The abstract should not be too long and should provide the reader with a good understanding what you are writing about. Academic papers are not like novels where you keep the reader in suspense. To be effective in getting others to read your paper, be as open and concise about your findings here as possible. Ideally, upon reading your abstract, the reader should feel he / she must read your paper in entirety.
---

<!-- First: Set your default preferences for chunk options: -->

<!-- If you want a chunk's code to be printed, set echo = TRUE. message = FALSE stops R printing ugly package loading details in your final paper too. I also suggest setting warning = FALSE and checking for warnings in R, else you might find ugly warnings in your paper. -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')
# Note: Include = FALSE implies the code is executed, but not printed in your pdf.
# warning and message = FALSE implies ugly messages and warnings are removed from your pdf.
# These should be picked up when you execute the command chunks (code sections below) in your rmd, not printed in your paper!

# Lets load in example data, and see how this can be stored and later called from your 'data' folder.
if(!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)

```


<!-- ############################## -->
<!-- # Start Writing here: -->
<!-- ############################## -->

#load in data:
```{r}
london_weather <- read_csv("data/london_weather.csv")

```

#convert date column 
```{r}
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 2/code/convert_date_column.R")
london_weather <- convert_date_column(london_weather, "date")
```

#cloud cover bar chart
```{r}
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 2/code/plot_daily_cloud_cover.R")
a <- plot_daily_cloud_cover(london_weather)
a
```

#precipitation bar chat
```{r}
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 2/code/plot_daily_precipitation.R")
b<- plot_daily_precipitation(london_weather)
b
```

#daily sunshine 
```{r}
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 2/code/plot_daily_sunshine.R")
c<-plot_daily_sunshine(london_weather)
c
```

#table 
```{r}
source("/Users/ryanyoung/Desktop/Data Science/22575480/Question 2/code/create_mean_table .R")
mean_table <- create_mean_table(london_weather)
print(mean_table)
```

